In [3]:
import numpy as np
import pandas as pd
import scipy
from scipy.spatial import distance
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from scipy.special import rel_entr

In [116]:
Predicted = pd.read_csv("./SpatialDWLS/Outputs/output_exp1.csv")
Target=pd.read_csv("./Data/exp1/target.csv")

In [117]:
Predicted

,Unnamed: 0,cell_ID,Ext_L23,Oligo_2,Astro_THAL_med,Inh_Sst,Inh_6,Inh_Meis2_3,Micro,Ext_L5_2,...,Astro_THAL_lat,Nb_1,LowQ_2,Inh_Vip,Astro_HPC,Ext_ClauPyr,OPC_2,Inh_5,Ext_Hpc_CA3,Inh_Meis2_4
0,1,exper1_location_0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,...,0.000000,0.000000,0.046651,0.0,0.000000,0.241654,0.0,0.030113,0.000000,0.093075
1,2,exper1_location_1,0.000000,0.0,0.000000,0.000000,0.029902,0.0,0.0,0.132391,...,0.000000,0.000000,0.000000,0.0,0.067751,0.211983,0.0,0.030278,0.000000,0.220460
2,3,exper1_location_2,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.106300,...,0.000000,0.000000,0.000000,0.0,0.000000,0.244637,0.0,0.054450,0.000000,0.146076
3,4,exper1_location_3,0.000000,0.0,0.000000,0.000000,0.039698,0.0,0.0,0.168052,...,0.000000,0.015813,0.000000,0.0,0.000000,0.345437,0.0,0.076114,0.000000,0.000000
4,5,exper1_location_4,0.000749,0.0,0.000000,0.044313,0.123040,0.0,0.0,0.087249,...,0.000000,0.032266,0.000000,0.0,0.000000,0.427217,0.0,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,2496,exper1_location_2495,0.000000,0.0,0.000000,0.000000,0.050808,0.0,0.0,0.190055,...,0.000000,0.000000,0.000000,0.0,0.000000,0.070642,0.0,0.000000,0.000000,0.000000
2496,2497,exper1_location_2496,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.055822,...,0.000000,0.000000,0.000000,0.0,0.000000,0.089714,0.0,0.000000,0.000000,0.000000
2497,2498,exper1_location_2497,0.012367,0.0,0.000000,0.000000,0.019959,0.0,0.0,0.160598,...,0.000000,0.000000,0.000000,0.0,0.031389,0.150848,0.0,0.037170,0.000000,0.000000
2498,2499,exper1_location_2498,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.080289,...,0.055973,0.000000,0.000000,0.0,0.000000,0.106552,0.0,0.071435,0.082434,0.000000
2499,2500,exper1_location_2499,0.000000,0.0,0.045534,0.000000,0.030433,0.0,0.0,0.103591,...,0.000000,0.000000,0.000000,0.0,0.000000,0.172870,0.0,0.015038,0.000000,0.000000

In [118]:
Target

,Unnamed: 0,cell_abundances_Inh_3,cell_abundances_Ext_Pir,cell_abundances_Oligo_2,cell_abundances_Astro_HYPO,cell_abundances_Ext_L25,cell_abundances_Astro_THAL_lat,cell_abundances_Ext_L5_1,cell_abundances_Ext_L23,cell_abundances_Micro,...,cell_abundances_Inh_Lamp5,cell_abundances_Inh_Pvalb,cell_abundances_Ext_L5_2,cell_abundances_Inh_6,cell_abundances_Astro_AMY,cell_abundances_Ext_ClauPyr,cell_abundances_Astro_HPC,cell_abundances_Astro_WM,cell_abundances_Nb_2,cell_abundances_Inh_5
0,exper1_location_0,0.0,0.0,0.0,0.444901,0.000000,0.000000,0.0,0.0,0.0,...,0.0,0.000000,0.156751,0.270233,0.434513,1.489322,0.692310,0.205472,0.918788,0.300265
1,exper1_location_1,0.0,0.0,0.0,0.238645,0.000000,0.000000,0.0,0.0,0.0,...,0.0,0.000000,0.265316,0.228353,0.342404,1.011573,0.969749,0.306405,0.606469,0.222796
2,exper1_location_2,0.0,0.0,0.0,0.201578,0.000000,0.000000,0.0,0.0,0.0,...,0.0,0.000000,0.453340,0.238994,0.325982,0.832885,0.621011,0.215489,0.709189,0.241834
3,exper1_location_3,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,...,0.0,0.216865,0.495463,0.247245,0.363599,0.618276,0.429339,0.161201,0.384629,0.111576
4,exper1_location_4,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,...,0.0,0.736312,0.246127,0.540297,0.555814,1.448712,0.286376,0.533452,0.370728,0.142814
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,exper1_location_2495,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,...,0.0,0.000000,0.722555,0.522003,0.473411,0.631128,0.745028,0.229575,0.816517,0.079654
2496,exper1_location_2496,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,...,0.0,0.000000,0.445345,0.345516,0.558277,0.779678,0.331490,0.533331,1.343361,0.201837
2497,exper1_location_2497,0.0,0.0,0.0,0.000000,0.264056,0.580711,0.0,0.0,0.0,...,0.0,0.000000,0.741683,0.326215,0.892642,0.893659,0.462853,0.216782,0.816210,0.148654
2498,exper1_location_2498,0.0,0.0,0.0,0.000000,0.327443,1.069664,0.0,0.0,0.0,...,0.0,0.000000,0.542741,0.335116,0.388449,1.071717,0.273387,0.260831,0.843416,0.252309
2499,exper1_location_2499,0.0,0.0,0.0,0.000000,0.261988,1.198782,0.0,0.0,0.0,...,0.0,0.000000,0.706756,0.333214,0.416046,1.212655,0.441773,0.253772,0.720189,0.135625

In [119]:
Predicted.drop(columns="Unnamed: 0", inplace=True)
Predicted.drop(columns="cell_ID", inplace=True)

In [120]:
Target.drop(columns="Unnamed: 0", inplace=True)

In [121]:
for i in range(len(Target)):
    Target.loc[i,:]=Target.loc[i,:]/Target.loc[i,:].sum()

In [122]:
for i in range(len(Predicted)):
    Predicted.loc[i,:]=Predicted.loc[i,:]/Predicted.loc[i,:].sum()

In [123]:
columns_p=[]
for i in range(Predicted.shape[1]):
    columns_p.append(Predicted.columns[i])

In [124]:
columns_t=[]
for i in range(Target.shape[1]):
    columns_t.append(Target.columns[i])

In [125]:
columns_p=sorted(columns_p)
columns_t=sorted(columns_t)

In [126]:
Predicted=Predicted[columns_p]
Target=Target[columns_t]

In [127]:
Target=Target.to_numpy()
Predicted=Predicted.to_numpy()

## Pearson Correlation

In [128]:
num_celltypes=Predicted.shape[1]
d = np.zeros(num_celltypes)
for i in range(0,num_celltypes):
    p=Predicted[:,i]
    t=Target[:,i]
    prs=(np.corrcoef(p,t,rowvar=False))
    d[i]=prs[0,1]

In [129]:
np.mean(np.nan_to_num(d))

0.6520017908885749

In [130]:
d

array([ 0.23184642,  0.65184619,  0.53007571,  0.2966366 ,  0.27978343,
        0.90238337,  0.58069955,  0.39195672,  0.68439373,  0.78431461,
        0.86622461,  0.97521332,  0.89453739,  0.58220553,  0.22608726,
        0.79049321,  0.66404812,  0.3027896 ,  0.37241963,  0.78690832,
        0.62728588,  0.95795298,  0.87555172,  0.77834857,  0.9246147 ,
        0.83860396,  0.66328314,  0.59850416,  0.0263772 ,  0.0664033 ,
        0.48813113,  0.790828  ,  0.73647362,  0.74199505,  0.86642146,
        0.9434798 ,  0.95812089,  0.93409531,  0.66739343,  0.92049617,
        0.80629905,  0.42459893,  0.64322165,  0.7848237 ,  0.69258808,
        0.85923514,  0.94312861,  0.61578487, -0.02081606])

## Jenson Shannon Divergence

In [131]:
jns=distance.jensenshannon(Predicted,Target,axis=1)
jns=jns[~np.isinf(jns).squeeze()]
np.mean(jns)

0.41611555621001134

## F1 Score, Precision, Recall

In [132]:
thresholds={0.001,0.01,0.1,0.2,0.3}

In [133]:
d = pd.DataFrame(0, index=np.arange(len(thresholds)), columns=["Precision","Recall","F1-score"])
d.index=thresholds
for t in thresholds:
    Predicted_logical=(Predicted>t).astype(int)
    Target_logical=(Target>t).astype(int)
    d.loc[t,"Precision"]=precision_score(Target_logical,Predicted_logical,average="micro")
    d.loc[t,"Recall"]=recall_score(Target_logical,Predicted_logical,average="micro")
    d.loc[t,"F1-score"]=f1_score(Target_logical,Predicted_logical,average="micro")

In [134]:
d

       Precision    Recall  F1-score
0.100   0.509660  0.614510  0.557196
0.200   0.331389  0.591027  0.424667
0.300   0.201533  0.573209  0.298217
0.010   0.789002  0.545275  0.644878
0.001   0.788351  0.527393  0.631994